# Generated by Django 4.2.16 on 2025-10-31 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding_app', '0017_candidate_career_objective_candidate_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('skills_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('education_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('experience_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('format_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('feedback', models.JSONField(blank=True, default=list, null=True)),
                ('improvement_tips', models.JSONField(blank=True, default=list, null=True)),
                ('missing_elements', models.JSONField(blank=True, default=list, null=True)),
                ('score_breakdown', models.JSONField(blank=True, default=list, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_analyses', to='onboarding_app.candidate')),
            ],
            options={
                'db_table': 'ats_analysis',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ats_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_files', to='onboarding_app.candidate')),
            ],
            options={
                'db_table': 'resume_files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ATSFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='ats_system.atsanalysis')),
            ],
            options={
                'db_table': 'ats_feedback',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
