# Generated by Django 5.2.6 on 2025-10-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_conversation',
            field=models.BooleanField(default=False),
        ),
    ]
