# Generated by Django 5.2.6 on 2025-10-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0003_conversation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='conversation_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
