# Generated by Django 5.2.6 on 2025-10-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0007_chatmessage_response_chatmessage_response_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='reply_to_id',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='response',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='response_date',
        ),
    ]
