# Generated by Django 4.2.16 on 2025-10-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0009_chatmessage_mentor_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
