# Generated by Django for signup flow changes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0013_candidate_resume_file_candidate_resume_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(max_length=50, default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(max_length=50, default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]