# Generated by Django 5.2.6 on 2025-11-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0021_candidate_difficulty_level_candidate_estimated_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='estimated_time',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='project_category',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='skills_involved',
        ),
    ]
