# Generated by Django 5.2.6 on 2025-11-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0024_add_project_upload_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='career_goals',
            field=models.TextField(blank=True, help_text='Career goals and objectives'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CGPA or percentage', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='department',
            field=models.CharField(blank=True, help_text='Academic department', max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='linkedin_profile',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Portfolio website URL'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills_json',
            field=models.JSONField(blank=True, help_text='JSON array of skills', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='verified',
            field=models.BooleanField(default=False, help_text='Profile verification status'),
        ),
    ]
