# Generated by Django 4.2.16 on 2025-10-31 10:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0017_candidate_career_objective_candidate_course_and_more'),
        ('skills_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillgapanalysis',
            name='target_role',
            field=models.CharField(default='Software Engineer', max_length=255),
        ),
        migrations.CreateModel(
            name='SkillUpgradeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('difficulty_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('course_url', models.URLField(blank=True)),
                ('priority_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills_management.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_recommendations', to='onboarding_app.candidate')),
            ],
            options={
                'db_table': 'skill_upgrade_recommendations',
                'ordering': ['-priority_score'],
            },
        ),
        migrations.CreateModel(
            name='SkillToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=255, unique=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('verification_method', models.CharField(choices=[('AI_VERIFIED', 'AI Verified'), ('CERTIFICATE', 'Certificate'), ('TEST_SCORE', 'Test Score'), ('PROJECT', 'Project'), ('MANUAL', 'Manual')], max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills_management.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_tokens', to='onboarding_app.candidate')),
            ],
            options={
                'db_table': 'skill_tokens',
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
