# Generated by Django 4.2.16 on 2025-11-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills_management', '0004_rename_created_at_skilltoken_verified_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='certificate_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
