# Generated by Django 5.2.6 on 2025-10-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('employer', 'Employer'), ('alumni', 'Alumni'), ('admin', 'Admin')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=100)),
                ('year_of_passout', models.IntegerField(blank=True, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('expertise', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('mentor_role', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_role', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'candidate',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('employer', 'Employer'), ('alumni', 'Alumni'), ('admin', 'Admin')], max_length=10)),
                ('sender_id', models.CharField(max_length=255)),
                ('receiver_id', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image')], default='text', max_length=10)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='sent', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('reply_to_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'onboarding_app_chatmessage',
                'ordering': ['timestamp'],
            },
        ),
    ]
