# Generated by Django 5.2.6 on 2025-10-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0002_chatmessage_is_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=255)),
                ('mentor_id', models.CharField(max_length=255)),
                ('messages', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conversation',
                'ordering': ['-last_updated'],
                'unique_together': {('student_id', 'mentor_id')},
            },
        ),
    ]
