# Generated by Django 5.2.6 on 2025-10-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0006_chatmessage_feedback_chatmessage_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
