# Generated by Django 5.2.6 on 2025-10-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0008_remove_chatmessage_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='mentor_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='mentor_ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
