# Generated by Django 4.2.16 on 2025-10-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0010_candidate_phone_candidate_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
