# Generated by Django 4.2.16 on 2025-10-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0011_candidate_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
    ]
