# Generated by Django 4.2.16 on 2025-10-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0012_remove_candidate_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_file',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
