# Generated by Django 4.2.16 on 2025-10-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0016_candidate_created_at_candidate_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='career_objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='course',
            field=models.CharField(blank=True, choices=[('btech', 'B.Tech / B.E.'), ('bsc', 'B.Sc'), ('bcom', 'B.Com'), ('ba', 'B.A'), ('bba', 'BBA'), ('bca', 'BCA'), ('mtech', 'M.Tech'), ('msc', 'M.Sc'), ('mba', 'MBA'), ('mca', 'MCA')], max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='course_type',
            field=models.CharField(blank=True, default='Full Time', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='grading_system',
            field=models.CharField(blank=True, choices=[('percentage', '% Marks of 100 Maximum'), ('cgpa', 'Scale 10 Grading System'), ('pass', 'Course Requires a Pass')], max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='marks_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='mobile_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='candidate',
            name='passing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='preferred_locations',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='registration_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_headline',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='candidate',
            name='specialization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='starting_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='university_institute',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_status',
            field=models.CharField(choices=[('fresher', "I'm a fresher"), ('experienced', "I'm experienced")], default='fresher', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('employer', 'Employer'), ('alumni', 'Alumni'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
