# Generated by Django 5.2.6 on 2025-11-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0020_create_project_idea_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='difficulty_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='project_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='project_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills_involved',
            field=models.TextField(blank=True, null=True),
        ),
    ]
