# Generated by Django 4.2.16 on 2025-11-03 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0017_candidate_career_objective_candidate_course_and_more'),
        ('skills_management', '0003_skillgapanalysis_target_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skilltoken',
            old_name='created_at',
            new_name='verified_on',
        ),
        migrations.RemoveField(
            model_name='skilltoken',
            name='verification_method',
        ),
        migrations.RemoveField(
            model_name='skilltoken',
            name='verification_status',
        ),
        migrations.AddField(
            model_name='skilltoken',
            name='confidence_score',
            field=models.FloatField(default=0.96),
        ),
        migrations.AddField(
            model_name='skilltoken',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='skilltoken',
            name='verification_source',
            field=models.CharField(choices=[('COURSE_COMPLETION', 'Course Completed'), ('ASSESSMENT_PASSED', 'Assessment Passed'), ('CERTIFICATE_UPLOAD', 'Certificate Uploaded'), ('ADMIN_VERIFIED', 'Admin Verified'), ('AI_VERIFIED', 'AI Verified')], default='AI_VERIFIED', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skilltoken',
            name='verified_by',
            field=models.CharField(default='FuSteps AI', max_length=100),
        ),
        migrations.AddField(
            model_name='userskill',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SkillSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('RESUME', 'Resume Upload'), ('CERTIFICATE', 'Course Certificate'), ('PROJECT', 'Project/Internship'), ('TEST', 'Test/Quiz Completion'), ('MANUAL', 'Manual Declaration')], max_length=20)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='skill_sources/')),
                ('source_url', models.URLField(blank=True, null=True)),
                ('extracted_skills', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding_app.candidate')),
            ],
            options={
                'db_table': 'skill_sources',
            },
        ),
    ]
